### PR TITLE
Add Java and Kotlin samples for Filter API:

### LINKED ISSUE #214: Create sample to demonstrate filter usage
It would be nice to have a Java and Kotlin sample that shows how the library API for filters works.

### PR DESCRIPTION
**Pull request by bocops**
- list all existing filters
 - create a new filter
 - add a keyword to an existing filter
 - delete a filter

 Closes #214

### CODE REVIEW

**Comment by andregasser** [comment]
Hello @bocops I have added another PR (https://github.com/andregasser/bigbone/pull/216) which improves the checkstyle code formatting rules. Could you review it quickly so I can merge after. After that, it would be nice if you could update your filter branch as well (run a `gradlew check` and fix the formatting issues reported). Thank you very much!

**Review by andregasser — CHANGES_REQUESTED** [review]
See my other comment.

**Comment by andregasser** [comment]
I've just now merged the new checkstyle rules into this branch.

**Comment by bocops** [comment]
@andregasser Done! :)

**Review by andregasser — APPROVED** [review]
Thanks!

**Pull request merged**
