### PR TITLE
Fix accidental poll removal on status edit.

### PR DESCRIPTION
**Pull request by bocops**
As detected via #166, editing a status containing a poll using `editStatus()` will remove the poll. This clarifies our documentation by stating that:
* poll statuses should **not** be edited using `editStatus()`
* all poll data that should not be changed during an edit via `editPoll()` needs to be retrieved from the existing status first.

Removes default values from two poll parameters in `editPoll()` to avoid an accidental change when editing.

Fixes one unrelated typo in the actual request.

### CODE REVIEW

**Review by andregasser — CHANGES_REQUESTED** [review]
The poll parameters should be refactored into a separat poll data class and the data class itself should then be placed in the *.entity.data package, as discussed in the associated issue.

**Comment by bocops** [comment]
I've now added the changes as discussed. Turns out, having two classes both named `Poll` is a bit problematic, though. My suggestion would be to rename the new one to `PollData`. @andregasser what do you think?

**Comment by andregasser** [comment]
Sure, that's fine! 👍🏻

**Comment by bocops** [comment]
@andregasser Done.

**Review by andregasser — APPROVED** [review]
Approved!

**Pull request merged**
