### PR TITLE
Fix: Add access token to sample code

### PR DESCRIPTION
**Pull request by lamrongol**
Fix sample code to add access token.
I don't use Kotlin so it may contains mistakes for StreamFederatedPublicTimeline.kt

### CODE REVIEW

**Comment by andregasser** [comment]
Hello @lamrongol Ghanks for your contribution! I guess you ran into an instance where the federated timeline feed required authentication? If yes, could you provide me the instance name? Thanks a lot.

**Comment by andregasser** [comment]
I can test fhe Kotlin part, no worries.

**Comment by andregasser** [comment]
Thanks for the details, will run some tests on my side today. Regarding the connection leakage error. We're already tracking this on this issue here: https://github.com/andregasser/bigbone/issues/123

Should you find more information on the root cause, please feel free to add your comment there. Thank you very much.

**Comment by andregasser** [comment]
Just run a `gradlew check` to make sure you meet syntax requirements 🙂

**Comment by lamrongol** [comment]
I committed the correction just before your comment and now "All checks have passed".

**Review by andregasser — APPROVED** [review]
Looks good! Thank you!

**Pull request merged**
