### PR TITLE
Reduce OkHttp exposure, enhance endpoint definition

### PR DESCRIPTION
**Pull request by bocops**
This PR deals with:

- OkHttp leakage described in #5
  - creating an OkHttp instance ourselves is no longer necessary when building a MastodonClient
  - users of `Media.postMedia()` will still have to deal with `okhttp3.MultipartBody`. Currently unsure if this is worth hiding and if so, how
- hardcoded path prefixes described in #35
  - it is now possible to call endpoints other than `/api/v1/...` - necessary for OAuth and later for V2 endpoints
  - method `postUrl()` allowing to post to arbitrary URLs was removed
  - URLs are now mostly created via `okhttp3.HttpUrl`, parameter lists via our own `Parameter` intead of as strings directly

Please review, because this has changes all over the place.

### CODE REVIEW

**Comment by andregasser** [comment]
Hello @bocops  Could you run a `gradle check` or `gradlew check` in your feature branch? There are some issues that should be fixed (like wildcard imports and such). No big things I've seen, but would be cool. Thx!

**Comment by bocops** [comment]
@andregasser Done :)

**Comment by andregasser** [comment]
Thanks! Did you see my other comments in this PR? Especially about the `Gson()` thing?

**Comment by bocops** [comment]
@andregasser I actually do not see any other comments here, Gson or otherwise.

**Comment by bocops** [comment]
With all the other changes coming in first, I think it is cleaner to close this PR and create a new one based on the updated main later. :)

**Pull request closed without merging**
