### PR TITLE
update Relationship model

### PR DESCRIPTION
**Pull request by G10xy**
By reading the API coverage, I decided to update the Relationship model. 
I would have wanted to update also the Account model but I did not understand what is missing...

### CODE REVIEW

**Comment by PattaFeuFeu** [comment]
This likely closes #19?

**Comment by PattaFeuFeu** [comment]
@G10xy Please try to link existing issues that you’re fixing.

Ideally, please also assign (or ask others to assign to you) issues you plan to work on.

Otherwise, there might be unnecessary duplicate work because multiple people might be working on the same issue without knowing of the others working on them.

**Comment by G10xy** [comment]
> This likely closes #19?

Yes, I think so

**Comment by G10xy** [comment]
> @G10xy Please try to link existing issues that you’re fixing.
> 
> Ideally, please also assign (or ask others to assign to you) issues you plan to work on.
> 
> Otherwise, there might be unnecessary duplicate work because multiple people might be working on the same issue without knowing of the others working on them.

You are totally right, sorry

**Review by andregasser — APPROVED** [review]
All good!

**Pull request merged**
