### PR TITLE
Enabled detekt formatting rules for Kotlin code

### PR DESCRIPTION
**Pull request by andregasser**

### CODE REVIEW

**Comment by andregasser** [comment]
This PR is currently work in progress. The fact that it currently fails is expected, due to the many formatting rules that are triggered. As soon as they are fixed, checks will be green again.

**Comment by bocops** [comment]
Is the idea to merge to deal with all failing tests in this PR directly, or merge later and then deal with failing tests in individual changes?

**Comment by andregasser** [comment]
In general, I would fix all the formatting issues in this branch to keep master green. 

But we should also merge the package renaming branch first, as it contains a lot of changes, then merge master again into this and start fixing the formatting issues here. 

Any objections?

**Comment by bocops** [comment]
That sounds like the best order - first the package renaming, then these formatting issues, then everything else.

**Review by bocops — APPROVED** [review]

**Pull request merged**
