### PR TITLE
remove "api/v1" path prefix hard-coding

### LINKED ISSUE #35: Hardcoded "/api/v1" path prefix
The path prefix to "api/v1" is currently hardcoded in [MastodonClient.kt](https://github.com/andregasser/mastodon4j/blob/13a67e42ba423907dbad02a01562caa5426c1a45/mastodon4j/src/main/kotlin/com/sys1yagi/mastodon4j/MastodonClient.kt#L20). This will be problematic once V2 endpoints need to be added, but is already an issue for the OAuth endpoints that aren't located under "/api".

The current workaround is to offer a separate `postUrl(String, Parameter)` method that interprets its string input as a full URL, whereas `post(String, Parameter)` interprets its input as additional path segments under "api/v1". Both the fact that the two methods have an identical signature and the fact that there's no check on whether the full URL even uses the same host as defined as `instanceName` can lead to issues down the line.

This could be solved by moving the full path to each endpoint out of MastodonClient and into each of its callers. At the same time, building the final URLs can be moved from doing it ourselves to using `okHttp.HttpUrl` and its builder throughout, which might prevent more bugs from happening.

I'm already working on the OkHttp part of #5, so I could tackle this in the process.

### PR DESCRIPTION
**Pull request by bocops**
Some endpoints exist at paths not starting with "api/v1", for example OAuth-related endpoints. More will follow as soon as v2 endpoints get implemented. No path prefix should be hard-coded in MastodonClient.

Fixing some warnings in touched files, especially redundant SAM-constructors.

Closes #35.

### CODE REVIEW

**Comment by bocops** [comment]
I don't know why Codecov complains about a reduced test coverage, or why it even considers the lines in question to be "added" in the first place. I believe that result can be ignored for this PR.

**Comment by andregasser** [comment]
I think I need to check its configuration once. Don't worry for the moment. 👍🏻

**Comment by bocops** [comment]
I believe so, yes. It is codecov/patch that is complaining about a lack of tests in added lines, although no lines were actually added. ;)

**Comment by andregasser** [comment]
Hello @bocops, master has been updated. Will review this as soon as the conflicts are resolved. Thanks for having a look. 👍

**Comment by bocops** [comment]
@andregasser conflicts are resolved now.

**Review by andregasser — APPROVED** [review]
All good! Thx 😀

**Pull request merged**
